# Conjoint analysis for choice modeling
### Jimmy Azar

## Introduction

We'll perform choice-based conjoint analysis in order to study customer preferences for attributes of a given type of product. The product in this case is a tablet. A survey was conducted in which customers were asked to select one from among three alternatives presented to them. The attributes are of course varied across the alternatives. Every customer was shown 15 such choice sets (each with 3 alternatives), and therefore 15 selections were recorded.

The attributes of a tablet are: brand, screen size (in inches), HD storage, RAM capacity, battery life, and price (in dollars). We would like to understand the importance of these attributes for customers.

## Data exploration

The data is provided in a comma-separated file named "tablets.txt". Read in the file and inspect the data. How many customers were surveyed in this data? Given that each customer was presented with 15 choice sets as evident in the data, and each choice set consisted of 3 alternatives to select from, does this explain the total number of rows in the dataset? 

The first 3 rows show that customer with id = 1 selected the first alternative when presented with the first choice set or question. This is indicated by a "1" in the variable "choice". Thus this customer prefers an iPad tablet with a 7-inch screen, 32GB storage, 4GB ram, 7-hour battery life, and a price of \$499 over a Surface tablet with characteristics shown in the second row or a Kindle with characteristics shown in the third row. In the second choice set, that same customer also preferred an iPad with certain characteristics over a Surface tablet or a Nexus tablet.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#data exploration
path_to_file = './data/tablets.txt'
data = pd.read_csv(path_to_file)	
data.head(6)

#data.shape #137*15*3 x 10

,consumer_id,choiceset_id,alternative_id,choice,brand,size,storage,ram,battery,price
0,1,1,1,1,iPad,sz7inch,st32gb,r4gb,b7h,499
1,1,1,2,0,Surface,sz10inch,st64gb,r2gb,b9h,399
2,1,1,3,0,Kindle,sz9inch,st16gb,r2gb,b8h,499
3,1,2,1,1,iPad,sz8inch,st32gb,r1gb,b8h,399
4,1,2,2,0,Surface,sz10inch,st128gb,r4gb,b7h,299
5,1,2,3,0,Nexus,sz7inch,st64gb,r1gb,b9h,199

## Multinomial logit model

We will build a conjoint multinomial model and train it over the data using the function **mnlogit()**.

Train the model using **mnlogit()** as shown below. Note that the "0" in the formula indicates that we do not wish to have an intercept included.

In [2]:
from statsmodels.formula.api import mnlogit

model = mnlogit('choice ~ 0 + brand + size + storage + ram + battery + price', data).fit()
model.summary();

Optimization terminated successfully.
         Current function value: 0.579977
         Iterations 6

## Parameter interpretation 

The attribute **summary()** reveals the coefficients associated with each attribute level. These coefficients can be compared (in sign and magnitude). Which brand has the highest (positive) coefficient? Also, does it make sense that the attribute "price" has a negative coefficient? Note that the attribute levels not appearing in the summary are reference levels and their coefficients are zero.

## Prediction

Use **predict()** to predict the probability of selecting each alternative for the given choice sets. We can therefore now make customer choice predictions for new alternatives (and their competition) before we release these into the market. However, we would also like to estimate the market share based on these choice predictions. For that purpose, we may use the softmax function to squash the outputs into the range $[0,1]$ such that the sum equals 1. 

If $U_j$ represents the (soft) label returned by the model for selecting some alternative $j$, then with $n$ alternatives being compared, the probability of selecting alternative $j$ is $p_j = \dfrac{exp(U_j)}{exp(U_1)+exp(U_2)+...+exp(U_n)}$, $j \in \{1,2,...,n\}$ (softmax)

The probabilities sum up to 1: $(p_1+p_2+...+p_n=1)$

Write a function that predicts the market share for alternatives appearing in a dataset which should be provided as input to the function, in addition to the model used. The functions will return the market shares which are just the probabilities above which should sum up to 1.

Suppose you want to test out the market shares for 4 alternatives which we will select from the original data (alternatives shown below). Use the trained model and the function **predict_share()** to estimate the market share of each alternative, and add these as a final column (after "price"). Show the resulting data frame. 

Finally, copy this data frame to a new one called "data_new" and change the amount of RAM for the iPad to 4GB instead of 2GB; what are the predicted market shares for the four competing alternatives in this new dataset?

In [3]:
#prediction
def predict_share(model, data):
    #...
    #...
    return #...

In [4]:
data_market = data.loc[[21,22,45,85],['brand','size','storage','ram','battery','price']].copy() 
data_market

      brand     size  storage   ram battery  price
21  Surface  sz8inch  st128gb  r4gb     b8h    499
22   Kindle  sz8inch   st32gb  r1gb     b7h    199
45   Galaxy  sz8inch   st64gb  r4gb     b7h    499
85     iPad  sz7inch   st64gb  r2gb     b8h    499

In [5]:
#prediction
def predict_share(model, data):
    df = data.copy()
    df['alternative'] = model.predict(df)[1]
    df['alternative'] = np.exp(df['alternative'])
    df['alternative'] = df['alternative']/df['alternative'].sum() 
    return df['alternative'] #Series
   
data_market = data.loc[[21,22,45,85],['brand','size','storage','ram','battery','price']].copy() 
data_market['predicted_share'] = predict_share(model, data_market)
data_market

#alternatively: append the Series to the data frame without copying it first
#data_market = data_market.assign(market = predict_share(model,data_market)) 

data_new = data_market.copy()
data_new.loc[85,'ram'] = 'r4gb'
data_new['predicted_share'] = predict_share(model, data_new)
#data_new

## Willingness-to-pay

From the parameter (coefficient) estimates of the model, we may compute how much a consumer would be willing to pay for a specific attribute level (such as 9-hour battery life). We just need to calculate the ratio of the coefficient for the specific attribute level to the coefficient of price (in absolute value). 

How much is the average consumer willing to pay in dollars to change tablet brand from Galaxy to iPad (all else fixed)? How much is a consumer willing to pay for an upgrade from 1GB to 4GB RAM? What about an upgrade from a 7-inch screen to a 9-inch screen?

In [6]:
#willingness-to-pay
model.params

galaxy_to_ipad = (model.params.loc['brand[Galaxy]'] - model.params.loc['brand[iPad]'])/model.params.loc['price']
galaxy_to_ipad[0]

r1gb_to_r4gb = (0 - model.params.loc['ram[T.r4gb]'])/model.params.loc['price']
r1gb_to_r4gb[0] 

sz7inch_to_sz9inch = (model.params.loc["size[T.sz7inch]"] - model.params.loc["size[T.sz9inch]"])/model.params.loc["price"]
sz7inch_to_sz9inch[0];